#!/bin/bash
#
# pop-up calendar for dzen
#
# based on (c) 2007, by Robert Manea
# http://dzen.geekmode.org/dwiki/doku.php?id=dzen:calendar
# modified by urukrama, steelcowboy
#

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`

(
# current month, highlight header and today
cal | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg(#FFFFFF)^bg(#FF3D00)\1/;
s/(^|[ ])($TODAY)($|[ ])/\1^bg(#DD2C00)^fg(#F6F9FF)\2^fg(#FFFFFF)^bg(#FF3D00)\3/"
) | dzen2 -fg '#FFFFFF' -bg '#FF3D00' -fn 'xft:Droid Sans Mono:size=10' -x "1155" -y \
"30" -w "160"  -l 7 -e 'onstart=uncollapse;button1=exit;button3=exit' -p 5

